// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iRLeagueDatabaseCore.Models;

namespace iRLeagueDatabaseCore.Migrations
{
    [DbContext(typeof(LeagueDbContext))]
    [Migration("20220308133854_EmptyDb")]
    partial class EmptyDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");
#pragma warning restore 612, 618
        }
    }
}
