name: .NET

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    env:
      BUILD_CONFIG: Release

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:        
        # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql root password: 'TestPass123!'
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: 'TestDatabase'
    - name: Set secrets
      run: dotnet user-secrets set 'ConnectionStrings:ModelDb' 'server=localhost;database=TestDatabase;user=root;password=TestPass123!' --project iRLeagueApiCore.UnitTests
    #- name: Grant user access
    #  run: mysql -u 'testuser' -p 'TestPass123!' < GRANT ALL PRIVILEGES ON *.* TO 'testuser'@'%';
    - name: Add Nuget Source
      run: dotnet nuget add source https://nuget.pkg.github.com/SSchulze1989/index.json --username SSchulze1989 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c $BUILD_CONFIG --no-restore
    - name: Test
      run: dotnet test -c $BUILD_CONFIG --no-build --verbosity normal
