name: .NET

on:
  push:
    tags: 
      - "*"

jobs:
  publish:

    runs-on: ubuntu-latest

    env:
      BUILD_CONFIG: Release
      TEST_USER: root
      TEST_PASSWORD: TestPass123!
      TEST_DATABASE: TestDatabase
      TEST_PROJECT: test/DbIntegrationTests

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:        
        # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql root password: $TEST_PASSWORD
        # MYSQL_DATABASE - name for the default database that is created
        mysql database: $TEST_DATABASE
    - name: Set secrets
      run: dotnet user-secrets set "ConnectionStrings:ModelDb" "server=localhost;database=$TEST_DATABASE;user=$TEST_USER;password=$TEST_PASSWORD" --project $TEST_PROJECT
    - name: Add Nuget Source
      run: dotnet nuget add source https://nuget.pkg.github.com/SSchulze1989/index.json --username SSchulze1989 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c $BUILD_CONFIG --no-restore
    - name: Test
      run: dotnet test -c $BUILD_CONFIG --no-build --verbosity normal
    - name: Publish
      run: dotnet nuget push **\*.nupkg -s github --skip-duplicate
